"use client";

import { use, useCallback, useEffect, useState, type FormEvent } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowLeft, CircleGauge, Clock3, FileText, MapPin, Network, Plus, Send, ShieldAlert, UserRound } from "lucide-react";
import type { Severity } from "@securewatch/shared";
import { api } from "@/lib/api";
import { formatDate } from "@/lib/utils";
import { SeverityBadge } from "@/components/severity-badge";
import { Button } from "@/components/ui/button";
import { EmptyState, ErrorState, LoadingState } from "@/components/states";

type Data = Record<string, unknown>;

export default function DetailPage({params}:{params:Promise<{section:string;id:string}>}) {
  const {section,id}=use(params);const router=useRouter();const [data,setData]=useState<Data|null>(null);const [error,setError]=useState("");const [saving,setSaving]=useState(false);
  const singular=section==="alerts"?"alert":section==="incidents"?"incident":"record";
  const load=useCallback(async()=>{setError("");try{setData(await api(`/api/v1/${section}/${id}`));}catch(e){setError(e instanceof Error?e.message:"Unable to load record");}},[section,id]);
  useEffect(()=>{const initial=setTimeout(()=>void load(),0);return()=>clearTimeout(initial);},[load]);
  const addNote=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setSaving(true);const form=event.currentTarget;const content=new FormData(form).get("content");try{await api(`/api/v1/${section}/${id}/notes`,{method:"POST",body:JSON.stringify({content})});form.reset();await load();}finally{setSaving(false);}};
  const updateStatus=async(status:string)=>{await api(`/api/v1/${section}/${id}`,{method:"PATCH",body:JSON.stringify({status})});await load();};
  const createIncident=async()=>{if(!data)return;const result=await api<{id:string}>("/api/v1/incidents",{method:"POST",body:JSON.stringify({title:`Incident: ${String(data.title)}`,description:String(data.description),severity:data.severity,alertIds:[id]})});router.push(`/dashboard/incidents/${result.id}`);};
  if(error)return <ErrorState message={error} retry={load}/>;if(!data)return <LoadingState/>;if(!["alerts","incidents"].includes(section))return <EmptyState title="Unsupported record"/>;
  const events=section==="alerts"?(data.events as Array<Data>??[]).map((link)=>link.event as Data):(data.events as Array<Data>??[]).map((link)=>link.event as Data);
  const notes=(data.notes as Array<Data>)??[];
  return <>
    <Link href={`/dashboard/${section}`} className="mb-5 inline-flex items-center gap-2 text-xs text-slate-500 hover:text-slate-300"><ArrowLeft className="h-4 w-4"/>Back to {section}</Link>
    <header className="panel overflow-hidden"><div className="border-b border-white/[.06] bg-gradient-to-r from-white/[.025] to-transparent p-6"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-start"><div><div className="mb-3 flex items-center gap-2"><SeverityBadge severity={data.severity as Severity}/><span className="rounded-full border border-white/10 px-2 py-1 text-[10px] text-slate-400">{String(data.status)}</span></div><h1 className="text-2xl font-semibold tracking-tight">{String(data.title)}</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-400">{String(data.description)}</p></div><div className="flex flex-wrap gap-2">{section==="alerts"&&<Button onClick={createIncident}><Plus className="h-4 w-4"/>Create incident</Button>}<select value={String(data.status)} onChange={(e)=>void updateStatus(e.target.value)} className="h-10 rounded-lg border border-white/10 bg-[#111927] px-3 text-xs outline-none">{(section==="alerts"?["OPEN","INVESTIGATING","CONTAINED","RESOLVED","FALSE_POSITIVE"]:["NEW","INVESTIGATING","CONTAINMENT","ERADICATION","RECOVERY","CLOSED"]).map((status)=><option key={status}>{status}</option>)}</select></div></div></div>
      <div className="grid divide-y divide-white/[.06] sm:grid-cols-2 sm:divide-x sm:divide-y-0 lg:grid-cols-4">{[[CircleGauge,"Risk score",`${String(data.riskScore??"—")}/100`],[ShieldAlert,"Detection rule",data.detectionRule??"Correlated investigation"],[UserRound,"Affected identity",data.affectedUser??(Array.isArray(data.linkedUsers)?data.linkedUsers.join(", "):"—")],[Network,"Source IP",data.ipAddress??(Array.isArray(data.linkedIpAddresses)?data.linkedIpAddresses.join(", "):"—")]].map(([Icon,label,value])=>{const I=Icon as typeof CircleGauge;return <div key={String(label)} className="p-5"><I className="h-4 w-4 text-cyan-300"/><p className="mt-3 text-[10px] uppercase tracking-wider text-slate-600">{String(label)}</p><p className="mt-1 truncate text-sm font-medium">{String(value)}</p></div>})}</div>
    </header>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1.6fr_1fr]">
      <section className="panel overflow-hidden"><div className="border-b border-white/[.06] p-5"><h2 className="text-sm font-semibold">Evidence timeline</h2><p className="mt-1 text-xs text-muted">Correlated security events in chronological order</p></div>{events.length===0?<p className="p-8 text-center text-sm text-muted">No linked events</p>:<div className="divide-y divide-white/[.05]">{events.map((event)=><div key={String(event.id)} className="flex gap-4 p-5"><div className="relative"><div className="grid h-8 w-8 place-items-center rounded-full border border-cyan-300/20 bg-cyan-300/[.07]"><Clock3 className="h-3.5 w-3.5 text-cyan-300"/></div></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-medium">{String(event.eventType).replaceAll("_"," ")}</p><SeverityBadge severity={event.severity as Severity}/></div><p className="mt-2 text-xs text-slate-500">{formatDate(String(event.timestamp))} · {String(event.source)} · Risk {String(event.riskScore)}/100</p><div className="mt-3 flex flex-wrap gap-3 text-[11px] text-slate-500">{Boolean(event.ipAddress)&&<span className="flex items-center gap-1"><Network className="h-3 w-3"/>{String(event.ipAddress)}</span>}{Boolean(event.country||event.city)&&<span className="flex items-center gap-1"><MapPin className="h-3 w-3"/>{[event.city,event.country].filter(Boolean).join(", ")}</span>}</div></div></div>)}</div>}</section>
      <div className="space-y-4"><section className="panel p-5"><h2 className="text-sm font-semibold">Recommended defensive actions</h2><div className="mt-4 space-y-3 text-xs leading-5 text-slate-400">{["Validate the affected identity and source context.","Contain exposed credentials or keys if compromise is plausible.","Review linked events before blocking shared infrastructure.","Record evidence and remediation decisions in the case timeline."].map((item,index)=><div className="flex gap-3" key={item}><span className="font-mono text-cyan-300">0{index+1}</span><p>{item}</p></div>)}</div></section><section className="panel overflow-hidden"><div className="border-b border-white/[.06] p-5"><div className="flex items-center gap-2"><FileText className="h-4 w-4 text-cyan-300"/><h2 className="text-sm font-semibold">Analyst notes</h2></div></div><div className="max-h-72 divide-y divide-white/[.05] overflow-y-auto">{notes.length===0?<p className="p-5 text-xs text-muted">No investigation notes yet.</p>:notes.map((note)=><div key={String(note.id)} className="p-4"><p className="text-xs leading-5 text-slate-300">{String(note.content)}</p><p className="mt-2 text-[10px] text-slate-600">{String((note.author as Data)?.name??"Analyst")} · {formatDate(String(note.createdAt))}</p></div>)}</div><form onSubmit={addNote} className="border-t border-white/[.06] p-4"><textarea name="content" required maxLength={10000} rows={3} className="w-full resize-none rounded-lg border border-white/10 bg-black/10 p-3 text-xs outline-none focus:border-cyan-400/50" placeholder={`Add an investigation note to this ${singular}…`}/><Button className="mt-2 w-full" size="sm" disabled={saving}><Send className="h-3.5 w-3.5"/>{saving?"Saving…":"Add note"}</Button></form></section></div>
    </div>
  </>;
}
